services:
  postgres:
    image: postgres:16-alpine
    container_name: otp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: otp_challenge
      POSTGRES_USER: otp_user
      POSTGRES_PASSWORD: otp_pass_dev
    ports:
      - "5432:5432"
    volumes:
      - otp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otp_user -d otp_challenge"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  otp_pgdata: